### ISSUE TITLE
Hitting a few issues - Trying to work around problems

### ISSUE THREAD

**Issue by rhastie** [networkop/nmos-kubernetes#1]
@networkop I'm currently working round some changes to the upstream installs and I was hope for your assistance here:

1. Worked round errors on "ConfigInLine" on command: `helm install metallb metallb/metallb -f values.yaml`

Using: New "resource.yaml" file
```
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip
  namespace: metallb
spec:
  ipAddressPools:
  - default-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb
spec:
  addresses:
  - 198.51.100.0/24
``` 

Follwed by:
```
kubectl create namespace metallb
helm install metallb metallb/metallb --namespace metallb
kubectl apply -f resources.yaml
``` 

2. Worked round error with: `kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.4.0" | kubectl apply -f -`

Using following as alternative: `kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/experimental-install.yaml`

3. Now stuck on k8s_gateway install. I get the following error when executing: `helm install exdns -f dns-values-http.yml k8s_gateway/k8s-gateway`

```
C:\nmos-kubernetes>helm install exdns -f dns-values-http.yml k8s_gateway/k8s-gateway
Error: INSTALLATION FAILED: template: k8s-gateway/templates/deployment.yaml:38:45: executing "k8s-gateway/templates/deployment.yaml" at <uniq>: error calling uniq: Cannot find uniq on type string

C:\nmos-kubernetes>helm install exdns -f dns-values-http.yml k8s_gateway/k8s-gateway --dry-run
Error: INSTALLATION FAILED: template: k8s-gateway/templates/deployment.yaml:38:45: executing "k8s-gateway/templates/deployment.yaml" at <uniq>: error calling uniq: Cannot find uniq on type string
``` 

Any ideas? Any suggestions on the error?

**Comment by networkop** [comment]
```yaml
extraZonePlugins: 
  - name: forward
    parameters:  . 1.1.1.1:53 8.8.8.8:53
```

**Comment by rhastie** [comment]
@networkop Thanks - this has resolved the installation issue. I'll now continue with the process. Many Thanks
